# GSA - Genetic Stability Analyzer

In order to speed up processing time when running classification algorithms, it is often useful to choose only the most "best" genes to use.  There are various algorithms available to choose genes, however here we use Chi2 Select K best.  K is how many genes you wish to use for testing stability.  More genese is usually better, however again in order to speed up processing time we limit the number of genes used.  This program allows you to set a min and max number of genes and an interval.  This will in turn setup numpy arrays with class and the select number of genes for further processing by FASTR and FASTrand.

### Libraries
Must be pre-installed.  Recommended to use virtual environment.

In [1]:
import numpy as np
from random import sample, choice, uniform
from os import path, getcwd, makedirs
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import StratifiedKFold
from collections import Counter
from sklearn.metrics import mean_squared_error
from scipy.sparse.linalg import lsqr
from math import sqrt, floor
from sklearn import svm
from multiprocessing import Pool, cpu_count
from enum import Enum
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm

/Users/terek/.virtualenvs/py370/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Methods and Classes
This section defines all classes and methods used.  The corresponding methods and classes for each .py file found in `main/Python` are described here.

### NBC.py

The NBC.py file contains two classes: Model and NBC.  The Network-based supervised classification technique (NBC) is described in [Ahmet Ay et al](http://journals.sagepub.com/doi/abs/10.4137/CIN.S14025).  Briefly, for each gene, a model is constructed from the gene's neighbors.  The model is a function of the form:

gene_expressipn @ g = neigh1X + neigh2X +....neighNx + C

The set of expressions for all genes creates the expressio nmodel.

In [2]:
class Model:
    """The model constructed for a given class"""

    def __init__(self, X, label, epsilon=0.8):
        """Initializes the model for a given class.

        :param X: Training data for model. If array or matrix, shape [n_samples, n_features].
        :param label: Class label for the data.
        :param epsilon: epsilon value correlation cutoff
        """
        self._label = label
        self.X = np.array(X)

        correlations = np.corrcoef(self.X, y=None, rowvar=False)

        # Note: the mask is the graph.
        self.mask = (np.absolute(correlations) > epsilon)

        pool = Pool(processes=cpu_count())
        self.coefficients = pool.map(self.solver, [gene for gene in range(len(correlations))])
        pool.terminate()

        self.coefficients = np.array(self.coefficients)

    def solver(self, gene):
        """Uses least-square solver to compute coefficients for Ax=b, where
        A is an equation list created from the neighbors of a gene and b is
        the value of the gene.

        :param gene: The index of the gene to be solved for.
        :return: The coefficients of the equation (x) in Ax=b
        """
        mask = self.mask[gene]
        A = []
        b = []
        for sample in self.X:
            neighbors = [sample[neighbor] if (mask[neighbor] and (gene != neighbor))
                         else 0 for neighbor in range(len(mask))]
            neighbors.append(1)
            A.append(neighbors)
            b.append(sample[gene])
        A = np.array(A)
        b = np.array(b)
        x = lsqr(A, b)[0]
        return x.tolist()

    def expression(self, sample):
        """Returns a hypothetical expression level for a given sample.

        :param sample: Test sample
        :return: The hypothetical expression level of a given sample.
        """
        expression = []
        for gene in range(len(self.coefficients)):
            level = 0  # the expression level of a gene
            for neighbor in range(len(self.mask) - 1):
                level += self.coefficients[gene][neighbor] * sample[neighbor]
            level += self.coefficients[gene][len(self.mask)]
            expression.append(level)
        return np.array(expression)

    def label(self):
        """Returns the class label of the model.

        :return: The class label of the model.
        """
        return self._label


class NetworkBasedClassifier:
    """Classifier implementing the Network-based Classifier."""

    def __init__(self, epsilon=0.8):
        """Initializes the classifier.

        :param epsilon: epsilon value correlation cutoff.
        """
        self.models = []
        self.epsilon = epsilon

    def fit(self, X, y):
        """Fit the model using X as training data and y as target values.

        :param X: Training data. If array or matrix, shape [n_samples, n_features].
        :param y: Target values of shape = [n_samples]
        """
        y = np.array(y)
        X = np.array(X)
        for label in Counter(y):
            a_class = np.where(y == label)
            self.models.append(Model([X[i] for i in a_class[0]], label, self.epsilon))

    def predict(self, X):
        """Predict the class labels for the provided data.

        :param X: Test samples.

        :return: lass labels for each data sample.
        """
        pool = Pool(processes=cpu_count())
        classifications = pool.map(self.classification, [sample for sample in X])
        pool.terminate()
        return np.array(classifications)

    def score(self, X, y):
        """Returns the mean accuracy on the given test data and labels.

        :param X: Test samples.
        :param y: True labels for X.

        :return: Mean accuracy of self.predict(X) wrt. y.
        """
        y = np.array(y)
        X = np.array(X)
        correct = np.asarray(self.predict(X) == y)
        return np.sum(correct) / correct.shape[0]

    def classification(self, sample):
        """Returns the classification of the sample.

        :param sample: Test sample
        :return: The class label of the sample.
        """
        errors = []
        for model in self.models:
            error = sqrt(mean_squared_error(sample, model.expression(sample)))
            errors.append(error)
        min_index = errors.index(min(errors))
        return self.models[min_index].label()


### Alter.py
The Alter.py file contains all methods and helper methods used to alter expressions.  There are currently four methods to alter expressions:

1) Greedy - uses a greed strategy to select the top k genes that will produce the largest bad accuracy
2) All - alters all genes by some percent amount.
3) Subset - alters a subset of the genes selected via chi2 value
4) RandSubset - alters a subset of the genes selected randomly


In [3]:
class AlterStrategy:
    """Describes the alteration strategy used."""

    # Alter strategies included:
    ALL = 0
    SUB = 1
    RANDSUB = 2
    GREEDY = 3
    
    def __init__(self,
                 _type):
        self._type = _type
        if _type == AlterStrategy.ALL:
            self._name = "ALL"
        elif (_type == AlterStrategy.SUB):
            self._name = "SUB"
        elif (_type == AlterStrategy.RANDSUB):
            self._name = "RANDSUB"
        elif (_type == AlterStrategy.GREEDY):
            self._name = "GREEDY"
    
    def getType(self):
        return self._type
    
    def getName(self):
        return self._name
    
    def Accuracy(estimator, X, y, chosen, idx_to_change):
        # TODO: run multiple times and return avg accuracy
        result = []
        for x in X:
            alt = np.copy(x)
            # alter prev chosen
            for i in chosen:
                #alt[i] = choice([0, alt[i]*2]) 
                alt[i] = 0
            # alter new gene
            #alt[idx_to_change] = choice([0, alt[idx_to_change]*2]) 
            alt[idx_to_change] = 0
            result.append(alt)
        result = np.array(result)
        return estimator.score(result, y)

    '''Static method'''
    def RankGreedy(estimator, X, y):
        fileName = '{}greedyRank.npy'.format(estimator.getName())
        if (path.exists(path.join(gsa_path, fileName))):
            return
        print("GREEDY RANK INITIALIZER - THIS CAN TAKE A WHILE.")
        estimator.fit(X,y)
        notChosen = list(range(X.shape[1]))
        chosen = []
        for i in range(X.shape[1]):
            pool = mp.Pool(processes = mp.cpu_count())
            accuracy = pool.starmap(AlterStrategy.Accuracy, [(estimator, X, y, chosen, idx) for idx in notChosen])
            pool.terminate()
            a = [x for _,x in sorted(zip(accuracy, notChosen))]
            chosen.append(a[0])
            notChosen.remove(a[0])  
        np.save(path.join(gsa_path,fileName), chosen)
        
    def Subset(percent, X):
        """
        B/c genese are already ordered by chi2 rank we can choose top k to alter.
        """
        result = []
        idx = floor(X[0].size * percent)
        if idx <= 0:
            return X
        else:
            for x in X:
                alt = np.copy(x)
                for i in range(idx):
                    alt[i] = choice([0, alt[i]*2])
                result.append(alt)
            return np.array(result)

    def RandSubset(percent,X):
        result = []
        k = floor(X[0].size * percent)
        if k <= 0:
            return X
        else:
            indices = sample(range(X[0].size),k)
            for x in X:
                alt = np.copy(x)
                for i in indices:
                    alt[i] = choice([0, alt[i]*2])
                result.append(alt)
            return np.array(result)
        
    def All(percent, X):
        print(percent)
        result = []
        for x in X:
            print(x)
            alt = []
            for gene in x:
                _offset = gene * percent
                _low = gene - _offset
                _high = gene + _offset
                alt.append(choice([_low,_high]))
            result.append(alt)
            print(alt)
        return np.array(result)        
        
    def Greedy(percent, X, estimator):
        high = np.amax(X)
        low = np.amin(X)
        result = []
        k = floor(X[0].size * percent)
        if k <= 0:
            return X        
        else:
            file = path.join(gsa_path,'{}greedyRank.npy'.format(estimator.getName()))
            indices = np.load(file)
            for x in X:
                alt = np.copy(x)
                for i in indices[0:k:1]:
                    alt[i] = uniform(low, high)
                result.append(alt)
            return np.array(result)        
        
    def Alter(self, percent, X, estimator):
        if self._type == AlterStrategy.ALL:
            return AlterStrategy.All(percent, X)
        elif self._type == AlterStrategy.SUB:
            return AlterStrategy.Subset(percent, X)
        elif self._type == AlterStrategy.RANDSUB:
            return AlterStrategy.RandSubset(percent, X)
        elif self._type == AlterStrategy.GREEDY:
            return AlterStrategy.Greedy(percent, X, estimator)


#### Helpers

The strategy is to choose greedily, however because of the random choice from the Accuracy method strategy, different genese may be chose, thus affecting the order in which the rank returns.  In general, the top gene should be the top gene in all cases, but as it progresses the genese can switch.

### Common.py
These are files that are helpers for the main program.  They consist of two methods:
1) A method to order the K best ranked genes.  This is used in conjunction with Atler.py Subset method.
2) A method to cross validate.  This is different than normal cross validation in that the estimator is fit to correct data while the score is derived from altered data.

In [4]:
def SelectKBestRanked(k, X, y):    
    b = SelectKBest(chi2, k).fit(X, y)
    a = b.get_support(indices = True)
    a = [x for _,x in sorted(zip(b.scores_[a],a),reverse=True)]
    return np.array(a)

In [5]:
def crossValidate(estimator, X, y, alterStrat, percent=0, cv=10):
    scores = []
    skf = StratifiedKFold(cv)
    for train_index, test_index in skf.split(X, y):
        estimator.fit(X[train_index], y[train_index]) 
        accuracy = estimator.score(
            alterStrat.Alter(percent, X[test_index],estimator),
            y[test_index])
        scores.append(accuracy)
    return np.array(scores)

### Estimatory.py

In [6]:
class Estimator:
    """Describes the classifier chooser."""

    # Classifiers included in the chooser
    NBC = 0
    KNN = 1
    SVM = 2
    RF = 3
    NB = 4
    
    def __init__(self,
                 _type,
                 epsilon=0.8,
                 neighbors=1):
        """Initialize a NBF classifier.

        Args:
            eps: epsilon value
        """
        self._type = _type

        # create the classifier
        if _type == Estimator.NBC:
            self._classifier = NetworkBasedClassifier(epsilon)
            self._name = "NBC"
        elif (_type == Estimator.KNN):
            self._classifier = KNeighborsClassifier(neighbors)
            self._name = "KNN"
        elif (_type == Estimator.SVM):
            self._classifier = svm.LinearSVC()
            self._name = "SVM"
        elif (_type == Estimator.RF):
            self._classifier = RandomForestClassifier()
            self._name = "RF"
        elif (_type == Estimator.NB):
            self._classifier = GaussianNB()
            self._name = "NB"
    
    def getType(self):
        return self._type
    
    def getName(self):
        return self._name
    
    def fit(self, X, y):
        self._classifier.fit(X,y)
        
    def score(self, X, y):
        return self._classifier.score(X, y)
        
    def predict(self, X):
        return self._classifier.predict(X)

## START MAIN PROGRAM

###### Enter the series and feature_size to use
Must be all upper case. e.g. `"GSE27562"`

In [7]:
series = "GSE19804"
feature_size = 50
alterStrat = AlterStrategy(AlterStrategy.RANDSUB)
estimator = Estimator(Estimator.NBC)

### Get/Create Directories
Assumes this notebook is in `GenClass-Stability/main/notebooks/`

In [8]:
notebook_dir = getcwd();
main_dir = path.dirname(path.dirname(notebook_dir))
load_path = path.join(main_dir, "GSE", series)
gsa_path = path.join(main_dir,"GSA", series, str(feature_size))
if not path.exists(gsa_path):
    makedirs(gsa_path)

### Import Classes and Expressions
Load original data. Assumes SIT and custome GSE script have been run to import data.

In [9]:
classes =np.loadtxt(path.join(load_path, "classes.txt"), dtype=np.str, delimiter="\t")
exprs = np.loadtxt(path.join(load_path, "exprs.txt"), delimiter="\t")

Select K best genes for analysis.

In [10]:
a = SelectKBestRanked(feature_size, exprs, classes)

Get selected genes from expressions.

In [11]:
exprs = exprs[:, a]

Save the selected expression data for potential later use.

In [12]:
np.save(path.join(gsa_path,"exprs.npy"), exprs)
np.save(path.join(gsa_path,"classses.npy"), classes)

### Stability Test

In [13]:
if(alterStrat.getType() == AlterStrategy.GREEDY):
    AlterStrategy.RankGreedy(estimator, exprs, classes)

In [14]:
percents = np.arange(0,1.01,0.05)
accuracies = []
stds = []
for percent in percents:
    print ("Percent:", percent)
    scores = crossValidate(estimator, exprs, classes, alterStrat, percent, 10)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std()))
    accuracies.append(scores.mean())
    stds.append(scores.std())
accuracies = np.array(accuracies)
stds = np.array(stds)

result = np.column_stack((percents,accuracies,stds))

Percent: 0.0
Accuracy: 0.97 (+/- 0.04)
Percent: 0.05
Accuracy: 0.97 (+/- 0.04)
Percent: 0.1
Accuracy: 0.90 (+/- 0.08)
Percent: 0.15000000000000002
Accuracy: 0.88 (+/- 0.11)
Percent: 0.2
Accuracy: 0.84 (+/- 0.16)
Percent: 0.25
Accuracy: 0.78 (+/- 0.09)
Percent: 0.30000000000000004
Accuracy: 0.79 (+/- 0.14)
Percent: 0.35000000000000003
Accuracy: 0.69 (+/- 0.15)
Percent: 0.4
Accuracy: 0.72 (+/- 0.13)
Percent: 0.45
Accuracy: 0.70 (+/- 0.18)
Percent: 0.5
Accuracy: 0.67 (+/- 0.10)
Percent: 0.55
Accuracy: 0.63 (+/- 0.12)
Percent: 0.6000000000000001
Accuracy: 0.60 (+/- 0.13)
Percent: 0.65
Accuracy: 0.62 (+/- 0.15)
Percent: 0.7000000000000001
Accuracy: 0.59 (+/- 0.10)
Percent: 0.75
Accuracy: 0.55 (+/- 0.17)
Percent: 0.8
Accuracy: 0.48 (+/- 0.13)
Percent: 0.8500000000000001
Accuracy: 0.60 (+/- 0.09)
Percent: 0.9
Accuracy: 0.53 (+/- 0.11)
Percent: 0.9500000000000001
Accuracy: 0.56 (+/- 0.16)
Percent: 1.0
Accuracy: 0.61 (+/- 0.12)


In [15]:
fileName = '{}_{}_result.npy'.format(estimator.getName(), alterStrat.getName())
np.save(path.join(gsa_path, fileName), result)

In [16]:
print(result)

[[0.         0.96666667 0.04082483]
 [0.05       0.96666667 0.04082483]
 [0.1        0.9        0.08164966]
 [0.15       0.875      0.11334559]
 [0.2        0.84166667 0.16007811]
 [0.25       0.78333333 0.09279607]
 [0.3        0.79166667 0.13565684]
 [0.35       0.69166667 0.14930394]
 [0.4        0.71666667 0.13017083]
 [0.45       0.7        0.17559423]
 [0.5        0.66666667 0.09860133]
 [0.55       0.63333333 0.11902381]
 [0.6        0.6        0.13333333]
 [0.65       0.61666667 0.15      ]
 [0.7        0.59166667 0.1017213 ]
 [0.75       0.55       0.16749793]
 [0.8        0.48333333 0.13333333]
 [0.85       0.6        0.08975275]
 [0.9        0.525      0.10573815]
 [0.95       0.55833333 0.15833333]
 [1.         0.60833333 0.12388391]]


In [17]:
#list(zip(*list(result)))